default[:clojure][:user] = "vagrant"
default[:clojure][:group] = "vagrant"
default[:clojure][:home_dir] = "/home/vagrant"
default[:clojure][:classpath] = "export CLASSPATH=$CLASSPATH:/home/vagrant/.clojure_libs"
#default[:clojure][:branch] = "trunk"
